### ISSUE TITLE
issue on white themes

### ISSUE THREAD

**Issue by medicamin** [corecoding/Vitals#1]
Hi there,

The menu text is not readable on white gnome shell themes.

**Comment by corecoding** [comment]
What theme are you using? Also can you provide a screenshot?

**Comment by medicamin** [comment]
The theme is Arc Maia
Gnome: 3.28.2
Manjaro 17.1.11

Screenshot:
![screenshot_970517_103507](https://user-images.githubusercontent.com/17678405/43819104-cf915b4a-9af6-11e8-9231-606458f68b76.jpg)

**Comment by medicamin** [comment]
Yes, It fixes the issue. Thanks a lot

**Comment by inkss** [comment]
![image](https://user-images.githubusercontent.com/31947043/43827075-872b29d2-9b2b-11e8-879f-367280d9e557.png)

**Comment by corecoding** [comment]
#2 fixes the issue. I'm going to close this issue, but it will take about 15 days before you see it on extensions.gnome.org
