### ISSUE TITLE
Incorrect CPU Average Readings

### ISSUE THREAD

**Issue by testsieger73** [corecoding/Vitals#107]
Hi,

First of all thanks for this very useful tool!

I found that the processor average usage readings are incorrect. When my CPU is under full load, Vitals sometimes shows more than 100% usage. However, when the CPU is under normal load, readings are lower than in command line tools like htop.

CPU AMD Ryzen 5 3600
MoBo MSI X370 GP (beta BIOS 5JM)

**Comment by corecoding** [comment]
Closing in favor of #131
