### ISSUE TITLE
Not displaying on panel

### ISSUE THREAD

**Issue by abriel** [corecoding/Vitals#109]
Hi,

I completely don't see the monitoring on my panel. 
![Screenshot from 2019-10-10 15-20-48](https://user-images.githubusercontent.com/796085/66573432-f58d7b80-eb72-11e9-8373-6697fd56b77f.png)

Just with luck I found a black place on the panel, and able to see the app menu.

Please advise.

Arch linux, gnome 3.34.
Extension from extensions.gnome.org , for shell 3.34, version 24.

Thanks,

**Comment by kouros17** [comment]
I have the same issue on Manjaro. The add-on is there just doesn't show its icon on the panel.You have to choose some values first.

**Comment by abriel** [comment]
@kouros17 , 
Oh my god!!! I spent about a week trying to cleanup configuration and re-installing the add-on. Nothing did help. But... Eventually it is so simple!
I just did miss the moment when all metrics gone from the panel.
Ok, I re-add them, now I got it.. So much thanks to you!

How do you think, should we close this?

**Comment by kouros17** [comment]
> Oh my god!!! I spent about a week trying to cleanup configuration and re-installing the add-on. Nothing did help.
Μe too. :)

**Comment by corecoding** [comment]
Glad you figured it out. There is still an issue, perhaps. If all sensors are unchecked, there should be a default icon that displays so you have something to click on. The icon I use is an operating system provided icon, so perhaps gnome-icon-theme-symbolic is not installed. Can you check?

**Comment by abriel** [comment]
Hi @corecoding , here it is:
```
$ yaourt -Ss gnome-icon-theme-symbolic
extra/gnome-icon-theme-symbolic 3.12.0-5 [installed]
    GNOME icon theme, symbolic icons
```
I use Adwaita theme, which is default.

Thanks.

**Comment by corecoding** [comment]
Closing because I have not heard any other reports of this.
