### ISSUE TITLE
Fixed Italian translation

### ISSUE THREAD

**Issue by RAD750** [corecoding/Vitals#113]
Hi there, I have made several modifications to the Italian localisation of Vitals. Here is the modified .po file.

I'm sorry if I'm not supposed to send it via issues, but this is the first time I am contributing to an opensource project on Github so please do apologise. Thanks! 
[vitals.zip](https://github.com/corecoding/Vitals/files/3775266/vitals.zip)

**Comment by corecoding** [comment]
Thank you! This will be included in the next update.
