### ISSUE TITLE
Units are ellipsized after a shell restart 

### ISSUE THREAD

**Issue by terencode** [corecoding/Vitals#119]
After a shell restart, some units like GB, GHz, B/S are ellipsized.
It is fixed after moving the mouse over them.

**To Reproduce**
1. Restart gnome-shell
2. Notice some units are replaced by `...`

**Expected behavior**
Units are rendered correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/12665563/69478916-1266d100-0df8-11ea-8d6e-9fe6eaf44b3d.png)

**Desktop**
 - OS: ArchLinux
 - Gnome Version 3.34

**Additional context**
https://github.com/corecoding/Vitals/commit/ccfad6bcda068b9f57b665c6fc6b89fbe04af8a3 did not help.

**Comment by terencode** [comment]
With https://github.com/corecoding/Vitals/commit/53cb50c7889766c182c1027a5da99e104284c81f it sometimes works but not always.

**Comment by corecoding** [comment]
I contacted a gnome shell developer for this problem a while back. With 3.34, parts of gnome shell aren't updated /  refreshed as often to give it the speed we have grown to love. He suggested this.emit    this.emit('style-changed');   but didn't say where to put it. I just added it to the enable/disable area. Maybe it's fixed? Finger crossed.

**Comment by corecoding** [comment]
Never mind, this.emit isn't working. Anyhow, I think the issue now is when my laptop goes to external monitor (hi to lo dpi).. I notice other weird things (not related to Vitals) such as some buttons

**Comment by nebrelbug** [comment]
@corecoding any updates? Loving this extension but units are ellipsized every time I open up my computer :man_shrugging: :joy:

**Comment by corecoding** [comment]
With the recent changes I have made, I have seen the ellipses less and less. It's tough because there is no doubt something I can change in the code to prevent them, but I have no idea what. They started happening somewhere around Gnome 3.30 - without any changes in Vitals code. When the next version of Vitals is released, please let me know if they go away.

**Comment by terencode** [comment]
Yes, I don't see anything hidden right now on version 32 (is it a mistake? last version was 35: https://github.com/corecoding/Vitals/commit/38f8bb690b1c1d78538709b02a166b46f0a4dfc6)

**Comment by corecoding** [comment]
I had set version 35 so Ubuntu didn't update the extension with the the live version, erasing any uncommitted development changes. 35 was just me taking a guess at the next version number. 32 is the official next version number.

**Comment by blipk** [comment]
@corecoding you can try `St.Label.get_clutter_text().ellipsize = 0;` on the 'HotItem' labels

**Comment by corecoding** [comment]
Thank you for this tip. Added to develop branch. Let me know if it helps!

**Comment by corecoding** [comment]
Was anyone able to confirm this fix? (On develop branch). I think it is working!

**Comment by terencode** [comment]
I can't speak for myself because I couldn't already reproduce before but maybe it has to do with not using gdm lockscreen anymore...
However, switching to develop branch I notice big spacing with the first and last elements: 
![image](https://user-images.githubusercontent.com/12665563/83746799-eefec780-a65f-11ea-92f1-55423ae989c2.png)

**Comment by nebrelbug** [comment]
@corecoding may be worth noting that for some reason, I (on GNOME 3.36) only notice the RAM% as being ellipsized, not core temperature or CPU%

**Comment by terencode** [comment]
Wondering if we should close this, I personally don't get the problem anymore.

**Comment by corecoding** [comment]
I haven't seen it in a long while either. Closing for now.

**Comment by wmertens** [comment]
I'm seeing this. Gnome 42, was also happening in 41. When I freshly added the extension, it was fine. Now, it's like this 100% of the time.

None of the display settings make any difference. There's plenty of room on the top bar. On/off extension also makes no difference.

![image](https://user-images.githubusercontent.com/54934/170062355-e8abf565-d234-479f-92c5-40c216852773.png)

**Comment by wmertens** [comment]
oh wow - it turns out those ... are metrics that were no longer available. As soon as I selected one they were gone. Problem solved!
