### ISSUE TITLE
Unnecessary truncating of indicator data 

### ISSUE THREAD

**Issue by Techtiger255** [corecoding/Vitals#125]
Every now and then the indicator will shrink in size, even though there is plenty of visual space for it to occupy... I usually have all sensors disabled except network, CPU, and memory, I have memory and CPU always displayed. However, every 30-120 minutes the indicator shrinks and the details are truncated to 0 characters (sometimes 1 character) and "..." is displayed, the issue seems to be fixed when I reduce the number of things to be shown down to just processor or repeatedly spam the alphabetize switch. Why is this happening? And can it be easily fixed?

**Comment by corecoding** [comment]
Unfortunately this was introduced with the latest two Gnome shell releases. Please see #119 for a duplicate conversation. Sorry, wish there was more help.
