### ISSUE TITLE
Change memory usage label. 

### ISSUE THREAD

**Issue by vesterlay** [corecoding/Vitals#130]
Please change GB's label to GiB's, because in this extension and basically in linux, the memory usage value is being shown in Gibibytes. I know that GB is also correct, but it's rather used for Gigabytes.

**Comment by corecoding** [comment]
Thank you for calling this out. You are correct. I added support for binary and decimal reporting, with proper labels. Closing ticket for now, but if you want to check it out, try the develop branch.
