### ISSUE TITLE
Drop down menu not centered

### ISSUE THREAD

**Issue by shbach** [corecoding/Vitals#133]
**Describe the bug**

![image](https://user-images.githubusercontent.com/5298745/78291425-36d76600-74da-11ea-8985-659744422cf5.png)

Currently it seems like the drop down menu is centered based off the left side of the menu.

**Expected behavior**
The dropdown menu should be in the very center of the icons. Everything else in the top bar has their dropdown menu centered so this doesn't match.

**Desktop (please complete the following information):**
 - OS: Solus 4.1
 - Gnome Version 3.36

**Comment by shbach** [comment]
Actually, this seems to be an issue with more than one extension so it might be a problem with gnome extensions in general.

**Comment by vesterlay** [comment]
I have the same issue. It's caused by vitals, you can repair tray by disabling vitals and restarting gnome shell(alt+f2 -> r).

**Comment by corecoding** [comment]
Thank you for your bug report. Development is paused until my goal is met. Please see https://github.com/corecoding/Vitals/issues/134 for more info.

**Comment by corecoding** [comment]
Thanks for your bug report. The menu actually where I want it. Take a look at my screenshot, you are missing an arrow which may make my decision a little more apparent.
![Screenshot from 2020-05-03 15-17-30](https://user-images.githubusercontent.com/3803591/80927622-d09d6780-8d53-11ea-9805-47d195471028.png)
