### ISSUE TITLE
battery percentage false

### ISSUE THREAD

**Issue by x0rld** [corecoding/Vitals#135]
**Describe the bug**
I tried to use the battery monitoring but it always stays at 100%

**To Reproduce**
1 activate the battery monitoring
2 look at the battery capacity percentage
**Expected behavior**
the battery capacity percentage always stays at 99%
**Screenshots**
![image](https://user-images.githubusercontent.com/45242856/79058798-ba2f4f00-7c72-11ea-8994-2208e89e9db6.png)

**Desktop (please complete the following information):**
 - OS: [fedora 31
 - GNOME Shell 3.34.5

**Comment by corecoding** [comment]
Thank you for your bug report. Development is paused until my goal is met. Please see https://github.com/corecoding/Vitals/issues/134 for more info.

**Comment by corecoding** [comment]
Can you tell me which, if any, of the directories you have files in? 

 /sys/class/power_supply/BAT0
 /sys/class/power_supply/BAT1
 /sys/class/power_supply/BAT2 
etc...

**Comment by x0rld** [comment]
i have BAT0 with think symlink
`/sys/class/power_supply/BAT0 -> 
../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/
`

**Comment by x0rld** [comment]
the file capacity has the good value

**Comment by corecoding** [comment]
Can you share what is in the file?

**Comment by x0rld** [comment]
sure 
![image](https://user-images.githubusercontent.com/45242856/81447376-cf69a180-917c-11ea-8be7-31d8d174dfe1.png)

**Comment by corecoding** [comment]
Thanks! re the rest of the battery stats correct? Can you send me a screenshot of the battery section UI from Vitals?

**Comment by x0rld** [comment]
all the datas are here, I didn't find all the datas in /sys/class/power_supply/BAT0/capacity
![image](https://user-images.githubusercontent.com/45242856/81506777-0fee2a00-92f9-11ea-82e5-f5dbb3b8dd1d.png)

**Comment by corecoding** [comment]
Glad it is working. I should have realized this before, but Capacity is your battery health. 99% is good, meaning your battery has only degraded 1%. The Percentage is your battery level.
