### ISSUE TITLE
Storage shows "No data"

### ISSUE THREAD

**Issue by popey** [corecoding/Vitals#139]
**Describe the bug**
The storage category has "No data". I have followed the steps in https://github.com/corecoding/Vitals/wiki/Storage-has-no-items and seen issue #114 and this doesn't fix it. 

**To Reproduce**
1. Install Ubnutu 20.04 (on experimental ZFS support - possibly why?)
2. Install Vitals
3. Follow guide on https://github.com/corecoding/Vitals/wiki to add additional packages
4. Open Vitals, see "No data" next to storage

**Expected behavior**
I dunno what should appear there, as this is my first install of Vitals, but I expect something which suggests free space on the root filesystem.
**Screenshots**
![Screenshot from 2020-05-02 01-10-52](https://user-images.githubusercontent.com/1841272/80850051-d0954e80-8c11-11ea-8e7a-d7b4137a7ad8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Gnome Version 3.36.1

**Additional context**
Possibly the fact I'm using ZFS which is new in 19.10, may be why?

**Comment by corecoding** [comment]
Thanks for the donation today! Can you try logging out and back in to your session?

**Comment by popey** [comment]
You're welcome. Thanks for the super fast response. Yes, restarting my session fixed it. Thanks.
![Screenshot from 2020-05-02 01-15-51](https://user-images.githubusercontent.com/1841272/80850189-99736d00-8c12-11ea-95cf-080dbe6c09bf.png)
