### ISSUE TITLE
Configurable top panel display

### ISSUE THREAD

**Issue by adarshkr532** [corecoding/Vitals#145]
Currently, the top panel shows only processor and system resources. However, I think it should be configurable according to the user. Like, I download stuff and like to know network speed after every moment and don't need to view system resources too frequently. So, it would have been better if I can view network speed without clicking every time. Similarly, if someone likes to see processor load, he needs to click the button every time.

**Comment by corecoding** [comment]
Please see the WiKi page. This is answered there. Thanks for downloading vitals.
