### ISSUE TITLE
can't it open in tweaks extensions

### ISSUE THREAD

**Issue by kkyflying** [corecoding/Vitals#146]
**Describe the bug**
can't it open in tweaks extensions

**To Reproduce**
1. glone the code
2. restart gnome
3. open the tweaks

**Screenshots**
![https://github.com/kkyflying/pictures/blob/master/Screenshot%20from%202020-05-22%2017-59-11.png](url)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04.4]
 - Gnome Version [3.82]

thank  you  ~

**Comment by kkyflying** [comment]
![](https://raw.githubusercontent.com/kkyflying/pictures/master/Screenshot%20from%202020-05-22%2017-59-11.png)

**Comment by corecoding** [comment]
What branch are you on? Can you give me the latest error you see in /var/log/syslog?

**Comment by kkyflying** [comment]
l  am on the develop brach,
```
but nothing at cat /var/log/syslog

➜  Vitals@CoreCoding.com git:(develop) journalctl --since="`date '+%Y-%m-%d %H:%M'`" -f | grep Vitals
5月 23 10:09:59  gnome-software[3026]: failed to create an app for user/*/extensions-web/shell-extension/Vitals_CoreCoding.com/*
5月 23 10:11:04  gnome-shell[2606]: JS WARNING: [~/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com/extension.js 159]: assignment to undeclared variable prefsButton
```

next l delete the developcode and  try to install by https://extensions.gnome.org/extension/1460/vitals/ ,
now is can open it 

thank you so much

**Comment by corecoding** [comment]
Glad it is working now. The develop branches are sometimes volatile.
