### ISSUE TITLE
preoccupied text size / fixed text size

### ISSUE THREAD

**Issue by dibg** [corecoding/Vitals#151]
**Describe the new feature you'd like**
Enabling network speed monitor makes things "dance" in the top bar since it goes from 3 digits to 1 digit resolution and vice versa expanding and contracting the top bar to fit the information. This is not the only instance this is happening cpu load is also another but not as apparent as network speed. This can be easly resolved by having the option to enable a specific text size. Let's say network speed will always use 3 digits resolution. Cpu will use 3 digits of spaces etc.

**Comment by corecoding** [comment]
Than you for writing in. Please add your comments to issue #55. There is a fix on the develop branch which I need more community feedback for before releasing it.
