### ISSUE TITLE
Hide the items inside the settings menu (top right)

### ISSUE THREAD

**Issue by Barraguesh** [corecoding/Vitals#152]
I would like to be able to hide the extension in the settings menu on the top right, like how Sound Input & Output Device Chooser works. I like the extension to monitor my vitals from time to time and it being displayed 24/7 is too annoying for me, so would be cool to be able to "hide it" in that menu so I access it whenever I want to without having it in my face all the time.

Like this:
![image](https://user-images.githubusercontent.com/25356150/85435738-719be800-b577-11ea-8e34-517e359e1cd1.png)

**Comment by corecoding** [comment]
Sorry, this is not compatible with how the selection of sensors works.
