### ISSUE TITLE
HDD temp

### ISSUE THREAD

**Issue by Arup65** [corecoding/Vitals#153]
Please add hard drive temp via udisks. Very full fledged extension otherwise keep the good work up.
Thanks

**Comment by corecoding** [comment]
Is the hdd temp you speak of available in the /sys/class/hwmon folders? 

Christopher Monahan

**Comment by Arup65** [comment]
On extensions like Freon and others the access is via udisks or via hddtemp.

**Comment by Strykar** [comment]
> Is the hdd temp you speak of available in the /sys/class/hwmon folders? Christopher Monahan Sent from my iPhone

IIRC, it's not exposed via sysfs because it needs to be read from SMART, and not all drives (in the past) supported SMART, hell, `hddtemp` can't pull temps off a SATA SSD, forget NVME.

It's why Freon groks it from `hddtemp`/`smartctl`/`udisks2`.

**Comment by corecoding** [comment]
Per the WiKi, Vitals reads from /proc and /sys to prevent system lag. I would entertain a PR if someone wanted to do the dev work, but a disclaimer would have to be added in Preferences explaining the system lag and not to report a bug for said lag.
