### ISSUE TITLE
Add a warning and change in color to red based on custom values for cpu and memory

### ISSUE THREAD

**Issue by munish259272** [corecoding/Vitals#156]
**Describe the new feature you'd like**
If possible, Please add feature to the user can enter custom values for memory and cpu and if those values exceed i should get a warning or the color of the icon in the tab changes to red.
for example if i set **custom threshold value** of memory = 80% then i should get a warning message or the color of the icon representing memory should change to red.

**Comment by corecoding** [comment]
Great idea! Can you chime in on issue #68 with your vote? Seems this idea could be picking up a bit of steam.
