### ISSUE TITLE
preference/system-monitor blocks the desktop function until clicks on it

### ISSUE THREAD

**Issue by hlechner** [corecoding/Vitals#162]
**Describe the bug**
When you right-click on Vitals extension on preference icon (or can be the system monitor one, doesn't matter) it block some desktop functionality like launch the `alt F2`, you must before click on screen (any part) to be able to launch Alt F2 (or other functionality).

Maybe you already seem that behavior in other way: when you open the preferences to use any switch or click on any button on it, you have to click twice.

**To Reproduce**
- Right click on Vitals menu
- Click on the preference button (bottom right one)
- hit: Alt + F2 (To try to open the `run a command`)

p.s: do not press esc, or click on other stuff between the step 2 to step 3.

**Expected behavior**
It should not block any desktop feature or need two clicks to be able to use the preference.

**Screenshots**
not applicable, since there is no visual difference.

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.7.11-arch1-1
 - Gnome Version 3.36

**Additional context**
I have tested some extensions, and just one do a similar buggy behavior: OpenWeather, the rest do not do that (including freon)

Thanks!

**Comment by KonstantMan** [comment]
Yeah i'm on Arch too ,and i have the same problem

**Comment by corecoding** [comment]
This has been fixed in the Gnome 40 version of Vitals. This means that if you are using Gnome 3.38 or lower, you will still see the error. Can anyone who is using Gnome 40 try out the master branch? (It is not in the extension store yet)

**Comment by corecoding** [comment]
This has been fixed in both v3.38 and v40. If you are using a version older than 3.38 it won't be fixed.
