### ISSUE TITLE
Error on Upgrade - Broken Install

### ISSUE THREAD

**Issue by SterlingButters** [corecoding/Vitals#173]
**Describe the bug**
Recent upgrade results in gnome shell extension ERROR. Was working flawlessly before that. 

**To Reproduce**
1. Attempt Upgrade/Install from https://extensions.gnome.org/extension/1460/vitals/

**Expected behavior**
Successful Upgrade/Installation

**Screenshots**
![image](https://user-images.githubusercontent.com/22737286/98953086-7840e280-24b9-11eb-9ef4-bd52789b3d7b.png)

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
GNOME Shell 3.36.4

**Additional context**
Maybe I can purge remove the installation and try again? Not sure how this would be done though

**Comment by corecoding** [comment]
I just created a Wiki entry for this issue. Please see https://github.com/corecoding/Vitals/wiki/Broken-after-upgrade

**Comment by SterlingButters** [comment]
Chris,
  
  ​
  
  ​Thanks for such a quick response and resolution!
