### ISSUE TITLE
Stops Working / Doesn't Work with 5950x CPU ?

### ISSUE THREAD

**Issue by lordbuddha** [corecoding/Vitals#179]
**Describe the bug**
It was working.  I swapped my CPU from 2700X to the 5950X.    After that swap, Vitals stopped functioning.   

In panel it just displays a triangle, it the setting it displays correct motherboard/CPU and 32 CPUs.  But there is no frequency displayed for any CPU.  There are no governors.

I tried the ALT-F2 r sequence and logged out / logged in. 

**To Reproduce**
1. Change to 5950X CPU

**Expected behavior**
It to be functional ;)

**Screenshots**
![Screenshot from 2020-12-11 11-49-27](https://user-images.githubusercontent.com/1159358/101839370-228a5380-3ba7-11eb-8659-d8decb3375e4.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Gnome Version whatever is latest that comes [with](url) 20.04

**Additional context**

**Comment by corecoding** [comment]
Can you share a screenshot of Vitals? I don't know what this screenshot is, but it is certainly not Vitals. :)

**Comment by lordbuddha** [comment]
Wrong project then.   Please close.
