### ISSUE TITLE
Port to other DEs?

### ISSUE THREAD

**Issue by officernice** [corecoding/Vitals#183]
I've recently been using Gnome as I just installed "stock" Fedora. Overall, the DE is not really my cup of tea. Too many hoops.

I don't really have any coding capabilities, but I would LOVE to see this extension in Xfce. Does that entail a huge conversion of code? Anyway, for the time being where I've used Gnome I really enjoyed this extension a ton. 

Have a great weekend. :)

**Comment by corecoding** [comment]
Thanks for the feedback. Unfortunately, I don't have a ton of free time to work on other DEs. Vitals is written in ES6 and I don't think other DEs use JS for development. I appreciate the thought. :)
