### ISSUE TITLE
Measurment units on/off option

### ISSUE THREAD

**Issue by ConstantMan** [corecoding/Vitals#184]
**Describe the new feature you'd like**
A measurement  units on/off option ,to  have a more minimal yet informative set of sensors 
For example i know that the fan speed  is measured in rpm's i don't need to see the unit to understand 

**Additional context**
If you can't add what i proposed as features please point out what should i change in the code to add them
![Screenshot from 2021-03-12 07-24-02](https://user-images.githubusercontent.com/56481040/110896288-f5fbea00-8303-11eb-84f9-95c9d95383af.png)

**Comment by Mossy93** [comment]
Yes! I would love to be able to turn off fans I'm not using.

**Comment by corecoding** [comment]
This feature has been added - I won't be adding this to the dropdown menus themselves, as some units of measurement are necessary because they change.
