### ISSUE TITLE
Pop! OS Cosmic error

### ISSUE THREAD

**Issue by ScizorsBLBC** [corecoding/Vitals#196]
The newest update to the extension is not working on Pop! OS newest update of cosmic. 
![Screenshot from 2021-07-13 17-00-20](https://user-images.githubusercontent.com/52053296/125540285-ecfa02d0-0231-4a92-8898-e748c8c2387f.png)

**Comment by corecoding** [comment]
Thank you for reaching out. I installed Cosmic after seeing your comment and Vitals is working for me. 

Can you take a look at /var/log/syslog and search for Vitals? If I can get a stack trace I can likely fix the issue.

**Comment by ScizorsBLBC** [comment]
Hello, I think this is what you were asking for, I am not sure tho. I am
not the most experienced linux user.


Jul 13 19:04:01 pop-os dbus-daemon[1799]: [session uid=1000 pid=1799]
Activating service name='org.gnome.ChromeGnomeShell' requested by ':1.439'
(uid=1000 pid=29908 comm="/usr/bin/python3 /usr/bin/chrome-gnome-shell
chrom" label="unconfined")
Jul 13 19:04:01 pop-os dbus-daemon[1799]: [session uid=1000 pid=1799]
Successfully activated service 'org.gnome.ChromeGnomeShell'
Jul 13 19:04:31 pop-os gnome-shell[30026]: Archive:
 /tmp/46N450.shell-extension.zip
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/extension.js
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/helpers/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/helpers/file.js
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/helpers/polyfills.js
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/icons/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/icons/battery-symbolic.svg
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/icons/cpu-symbolic.svg
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/icons/fan-symbolic.svg
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/icons/memory-symbolic.svg
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/icons/network-download-symbolic.svg
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/icons/network-symbolic.svg
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/icons/network-upload-symbolic.svg
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/icons/storage-symbolic.svg
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/icons/system-symbolic.svg
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/icons/temperature-symbolic.svg
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/icons/voltage-symbolic.svg
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/LICENSE
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/ca/
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/ca/LC_MESSAGES/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/ca/LC_MESSAGES/vitals.mo
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/ca/LC_MESSAGES/vitals.po
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/es/
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/es/LC_MESSAGES/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/es/LC_MESSAGES/vitals.mo
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/es/LC_MESSAGES/vitals.po
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/it/
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/it/LC_MESSAGES/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/it/LC_MESSAGES/vitals.mo
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/it/LC_MESSAGES/vitals.po
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/nl/
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/nl/LC_MESSAGES/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/nl/LC_MESSAGES/vitals.mo
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/nl/LC_MESSAGES/vitals.po
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/pl/
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/pl/LC_MESSAGES/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/pl/LC_MESSAGES/vitals.mo
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/pl/LC_MESSAGES/vitals.po
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/pt/
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/pt/LC_MESSAGES/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/pt/LC_MESSAGES/vitals.mo
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/pt/LC_MESSAGES/vitals.po
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/pt_BR/
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/pt_BR/LC_MESSAGES/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/pt_BR/LC_MESSAGES/vitals.mo
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/pt_BR/LC_MESSAGES/vitals.po
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/ru/
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/ru/LC_MESSAGES/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/ru/LC_MESSAGES/vitals.mo
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/ru/LC_MESSAGES/vitals.po
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/ru/README.md
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/sk/
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/sk/LC_MESSAGES/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/sk/LC_MESSAGES/vitals.mo
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/sk/LC_MESSAGES/vitals.po
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/tr/
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/tr/LC_MESSAGES/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/tr/LC_MESSAGES/vitals.mo
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/tr/LC_MESSAGES/vitals.po
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/vitals.pot
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/zh_CN/
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/zh_CN/LC_MESSAGES/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/zh_CN/LC_MESSAGES/vitals.mo
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/locale/zh_CN/LC_MESSAGES/vitals.po
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/menuItem.js
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/prefs.js
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/prefs.legacy.ui
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/prefs.ui
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/README.md
Jul 13 19:04:31 pop-os gnome-shell[30026]:    creating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/schemas/
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/schemas/gschemas.compiled
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/schemas/org.gnome.shell.extensions.vitals.gschema.xml
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/sensors.js
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/stylesheet.css
Jul 13 19:04:31 pop-os gnome-shell[30026]:   inflating:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/values.js
Jul 13 19:04:31 pop-os gnome-shell[30026]:  extracting:
/home/scizors/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
/metadata.json
Jul 13 19:04:31 pop-os gnome-shell[2460]: JS ERROR: Extension
Vitals@CoreCoding.com: Error: A different version was loaded previously.
You need to log out for changes to take effect.#012loadExtension
@resource:///org/gnome/shell/ui/extensionSystem.js:343:52#012callback
@***@***.***:///org/gnome/shell/ui/extensionDownloader.js:115:13
Jul 13 19:05:05 pop-os /usr/libexec/gdm-x-session[2222]: (EE) event4  -
Logitech MX Master 3: client bug: event processing lagging behind by 11ms,
your system is too slow
Jul 13 19:05:05 pop-os /usr/libexec/gdm-x-session[2222]: (EE) event4  -
Logitech MX Master 3: WARNING: log rate limit exceeded (5 msgs per 60min).
Discarding future messages.
Jul 13 19:05:06 pop-os touchegg[979]: libinput error: event4  - Logitech MX
Master 3: client bug: event processing lagging behind by 11ms, your system
is too slow
Jul 13 19:05:07 pop-os touchegg[979]: libinput error: client bug: timer
event4 debounce: scheduled expiry is in the past (-0ms), your system is too
slow
Jul 13 19:05:07 pop-os touchegg[979]: libinput error: client bug: timer
event4 debounce short: scheduled expiry is in the past (-13ms), your system
is too slow
Jul 13 19:05:07 pop-os /usr/libexec/gdm-x-session[2222]: (EE) client bug:
timer event4 debounce: scheduled expiry is in the past (-0ms), your system
is too slow
Jul 13 19:05:07 pop-os /usr/libexec/gdm-x-session[2222]: (EE) client bug:
timer event4 debounce short: scheduled expiry is in the past (-13ms), your
system is too slow

**Comment by corecoding** [comment]
Yes, this is exactly what I was looking for. Thank you. The specific error you are receiving is:
"A different version was loaded previously. You need to log out for changes to take effect."

I've had a few reports of this in the past when I updated Vitals. If you log out of your desktop and log back in, Vitals should start working. Worst case, if you uninstall it by clicking the red X, and re-install it as you did initially, it should start working again. It should even keep your previously selected menu bar sensors.

I'll ask the Gnome guys about this error so I can try to prevent it in the future.

**Comment by ScizorsBLBC** [comment]
Hey that worked, I did a reboot and now it's working as it did before, even has the previously selected preferences as you suspected it would!  Thank you for resolving this so quickly!
