### ISSUE TITLE
NVidia monitoring support

### ISSUE THREAD

**Issue by boniek83** [corecoding/Vitals#197]
**Describe the new feature you'd like**
I would like to monitor fan speed, temperature and gpu power draw.

**Additional context**
https://docs.nvidia.com/deploy/nvml-api/nvml-api-reference.html
nvidia-smi
https://developer.nvidia.com/nvapi

**Comment by corecoding** [comment]
Please see https://github.com/corecoding/Vitals/wiki/Can-you-add-support-for-my-GPU%3F for more information.  If the sensor information is available, please let me know.

**Comment by Poly2it** [comment]
Monitoring doesn't seem to be available with my 3060.
