### ISSUE TITLE
Gnome Shell 41 support

### ISSUE THREAD

**Issue by franjsco** [corecoding/Vitals#204]
When will it be available for GNOME 41?

![immagine](https://user-images.githubusercontent.com/33671357/135755620-22a9b596-a48a-46bf-9217-04c2afdac918.png)

**Comment by corecoding** [comment]
I will work on it this coming week. Hopefully it is easy to fix.

**Comment by corecoding** [comment]
A new version has been uploaded that supports Gnome 41.
