### ISSUE TITLE
Monitor Storage showing 'No Data'

### ISSUE THREAD

**Issue by manozzo** [corecoding/Vitals#207]
###
![vitals-storage-bug](https://user-images.githubusercontent.com/39735577/139719926-db2d5cfa-f028-4dc9-bbb8-b3607f431d66.png)
 I tried to change the path do the storage to get more specif, but didn't work.

**Comment by dorsi** [comment]
I've same problem with no data on the storage. Debian 11, Gnome 41.

**Comment by ttamttam** [comment]
Confirmed here with Debian 11.1 and Gnome 3.38.5

**Comment by corecoding** [comment]
I noticed that changing the path is broken in the current Vitals. I'll fix it.

Some of you may be experiencing this issue though: https://github.com/corecoding/Vitals/wiki/Storage-reporting-%22No-Data%22

**Comment by manozzo** [comment]
> I noticed that changing the path is broken in the current Vitals. I'll fix it.
> 
> Some of you may be experiencing this issue though: https://github.com/corecoding/Vitals/wiki/Storage-reporting-%22No-Data%22

**I made this and work for me! Thank you!!!** Ubuntu 20.04, GNOME 3.36.8

**Comment by ttamttam** [comment]
Thanks. The installation of the dependencies solved it. Cool.
A possible improvement would be for Vitals to check for the presence of the required software and somehow warn the user that some package may be missing?
Good job!

**Comment by corecoding** [comment]
Fixed ability to change storage path in gnome 40+, released in vitals 46
