### ISSUE TITLE
cannot make it work after installing

### ISSUE THREAD

**Issue by ZakiMohammad** [corecoding/Vitals#208]
**Describe the bug**
I had been using this for many days but today it got a new update and i installed the update, but after installing the update i dont seem to use it and  a red error button shows next to setting and uninstall buttons

**To Reproduce**
1. search for  'vitals Gnome extensions' in gnome website
2. Click on 'toogle to on'
3. then you can see

**Expected behavior**
showing stats in top bar

**Comment by corecoding** [comment]
https://github.com/corecoding/Vitals/wiki/Broken-after-upgrade
