### ISSUE TITLE
Gpu stats 

### ISSUE THREAD

**Issue by gfrcr** [corecoding/Vitals#214]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [x] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

I want to know if there is any config that I could make to show the gpu stats on vitals

**Comment by corecoding** [comment]
https://github.com/corecoding/Vitals/wiki/Can-you-add-support-for-my-GPU%3F

**Comment by corecoding** [comment]
There is no config that can bridge the gap from a command line utility to the vitals UI. Of course you can modify the source code to run the command - but as the Wiki says, it's not something that the public version of Vitals will do.
