### ISSUE TITLE
don't show fan RPM

### ISSUE THREAD

**Issue by Thunderultra** [corecoding/Vitals#215]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

why vitals don't show detail <RPM> fan?

### Steps to reproduce the unexpected behavior.

1.vitals 
2.select RPM average

### What distribution and version of Linux are you using?

ubuntu 21.10

### What version of Gnome are you using?

10.1

**Comment by corecoding** [comment]
Please take a look at this Wiki entry: https://github.com/corecoding/Vitals/wiki/Missing-voltage-or-fan-data
