### ISSUE TITLE
option to rename labels

### ISSUE THREAD

**Issue by tutanotaaa** [corecoding/Vitals#218]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

Option to rename labels?

**Comment by corecoding** [comment]
This is a duplicate of #83. Please chime in on that thread or give it a thumbs up. Thanks :)
