### ISSUE TITLE
power usage is set to 0.0w while plugged in, fully charged

### ISSUE THREAD

**Issue by stem-lg** [corecoding/Vitals#223]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

show power usage while plugged in (fully charged battery)

i got it working by accident one time (unplugged and plugged charger really quick)

### Steps to reproduce the unexpected behavior.

insert charger to laptop
wait for it to be fully charged
power usage goes to 0.0 w

### What distribution and version of Linux are you using?

fedora 35

### What version of Gnome are you using?

41.2

**Comment by corecoding** [comment]
Unfortunately, this is out of my control. The power usage percentage is calculated by the kernel. When the power cord is unplugged, it shows battery draw. When it is plugged in, it shows charging rate. When it is charged, it isn't using battery so it goes to 0.
