### ISSUE TITLE
Network icons, total downloaded/uploaded

### ISSUE THREAD

**Issue by den7007** [corecoding/Vitals#229]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

Is it possible to have the network icons differentiate between download/upload like how it is displayed in the dropdown menu? It just shows the cloud icon without the up/down arrow when at the top bar.

![February-11-2022](https://user-images.githubusercontent.com/68644291/153455980-fd364c4a-3ddd-4ba0-bdfa-978a31b58468.jpg)

Wondering also if possible to include total amount downloaded/uploaded for the session as another item under Network? And maybe an option to reset the counter whenever we choose?

**Comment by corecoding** [comment]
I have combined #230 with this ticket, and added the download/upload icon feature in the develop branch. It'll be released before the next Gnome version.

For the second request, I really like the idea. Do you mind creating another issue/ticket so we can track it separately? Thanks!
