### ISSUE TITLE
Hiding buttons in the extension window

### ISSUE THREAD

**Issue by amivaleo** [corecoding/Vitals#23]
Hi,

I would like not to have have buttons on the bottom (refresh, system-monitor, settings).
Will you add a toggle in the setting menu for hiding them?
In the extension.js file, I only need to comment the following two lines:
```
//        this.menu.addMenuItem(new PopupMenu.PopupSeparatorMenuItem());
//        this.menu.addMenuItem(item);
```
I don't know how to insert the toggle. :(

Let me know if you like this idea.

**Comment by corecoding** [comment]
This is a very simple change. I'd be curious to see if anyone else would like to see it? My only fear is someone turning off the controls and not knowing how to get back into the Preferences. Definitely keeping this issue open to get a consensus.

**Comment by corecoding** [comment]
Closing because no one else chimed in.
