### ISSUE TITLE
Typo (gibigyte -> gibibyte)

### ISSUE THREAD

**Issue by jose1711** [corecoding/Vitals#232]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

In `schemas/org.gnome.shell.extensions.vitals.gschema.xml` the string `gibigyte` should be renamed to `gibibyte`.

### Steps to reproduce the unexpected behavior.

n/a

### What distribution and version of Linux are you using?

not relevant

### What version of Gnome are you using?

not relevant

**Comment by corecoding** [comment]
Thank you! Fix is also in develop branch.
