### ISSUE TITLE
Temperature not showing in GNOME's panel

### ISSUE THREAD

**Issue by thegabriele97** [corecoding/Vitals#238]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

The temperature is not showing in GNOME's panel

![image](https://user-images.githubusercontent.com/35406071/155835908-6913e70e-01ee-49f7-86bd-3c184dc4e7a0.png)

![image](https://user-images.githubusercontent.com/35406071/155835943-0db0b744-1eff-442a-ba38-0b844597e786.png)

### Steps to reproduce the unexpected behavior.

1. Start your computer
2. Look at your GNOME top panel
3. (Same if you try to restart with ALT+F2 -> r)

### What distribution and version of Linux are you using?

Pop OS! 21.10

### What version of Gnome are you using?

40.4.0

**Comment by corecoding** [comment]
Vitals shows sensors that are available. If you see "..." in the menu bar it means you selected a sensor that was once available, and no longer is. If you click on any sensor from the drop-down (not just temperature) it will trigger removal of the missing sensor.
