### ISSUE TITLE
General icon on the panel

### ISSUE THREAD

**Issue by amivaleo** [corecoding/Vitals#24]
Hi,

Is there a way to show only a general icon the on the panel instead of having labels/refreshing numbers/etc?
I would like to have only a system-monitor icon on the top panel, without any additional info (meaning: no numbers).

Is this something you would like to code/to have as a feature? :)

**Comment by corecoding** [comment]
Please see issue #5 - seems to be a popular request. I will work on this next. Closing this issue because it is a duplicate. :)
