### ISSUE TITLE
Icon changed/incorrect in top bar after update

### ISSUE THREAD

**Issue by Dorro101** [corecoding/Vitals#242]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

The top bar has a temp icon with three dots adjacent, this was not the case before the update...
![Screenshot from 2022-03-16 20-53-23](https://user-images.githubusercontent.com/54166678/158595174-d7ce6014-279a-45ab-beb0-0359cde6577d.png)

### Steps to reproduce the unexpected behavior.

Is a permanent graphical change, not a crash per se...

### What distribution and version of Linux are you using?

Fedora 35

### What version of Gnome are you using?

41

**Comment by Dorro101** [comment]
Love your extension by the way, one of the first things I install after OS upgrade/change.

**Comment by corecoding** [comment]
Did you see https://github.com/corecoding/Vitals/wiki/Sensor-shows-%22...%22-in-menu-bar ? There was a bit of a restructure in how Temp, Fan and Volt are handled.

**Comment by Dorro101** [comment]
Thanks so much! Fixed!!! Now I feel like a right idiot who doesn't bother to RTFM....

Ciao
Dorian

**Comment by corecoding** [comment]
To be honest, you are certainly not the first person to ask this question. I am thinking I need to figure out a way to automatically remove "..." sensors. Of course, some may ask why the sensors disappeared, but I think it is one step in the right direction.
