### ISSUE TITLE
Data read(write)/sec is not display

### ISSUE THREAD

**Issue by shungo27** [corecoding/Vitals#246]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

Storage > Data read(write)/sec is not display.
![Screenshot from 2022-04-02 17-34-05](https://user-images.githubusercontent.com/7065076/161375499-971c9062-da7a-407f-9f8a-9470725cc015.png)

### Steps to reproduce the unexpected behavior.

1. install Vitals
$ sudo apt install gir1.2-gtop-2.0 lm-sensors
https://extensions.gnome.org/extension/1460/vitals/

* raspberry pi 4b 8gb
* SSD and HDD are connected to USB

### What distribution and version of Linux are you using?

raspberry pi OS 64bit Lite bullseye

### What version of Gnome are you using?

3.38

**Comment by corecoding** [comment]
Vitals reads /proc/diskstats and /proc/mounts - only when both of those device blocks can be matched does the read/write show. When using LVM, ZFS, etc this feature is not supported.

**Comment by shungo27** [comment]
thank you for information. I sloved this issue.

sensors.js
```
- this._storageDevice = '';
- this._findStorageDevice();
+ // this._storageDevice = '';
+ // this._findStorageDevice();

- if ('/dev/' + loadArray[2] == this._storageDevice) {
+ if (loadArray[2].match(/^sd.$/)) {
```

On my system all storage starts with "sd" so this was the solution.
