### ISSUE TITLE
Voltage and fans sensors not working?

### ISSUE THREAD

**Issue by amivaleo** [corecoding/Vitals#25]
Hi,

I have a dell xps 13.
Most of the sensors work apart from voltage and fans.
Do you know how to tackle this issue?

Thanks. :)

**Comment by corecoding** [comment]
I have a XPS 13 9360 and have the same issue. Vitals simply reports what is available in /price and /sys. For these machines, voltage and fans is not supported. I think there is a dell specific kernel module that doesn’t yet support our machines.

**Comment by amivaleo** [comment]
I see... ._.
