### ISSUE TITLE
Update won't run on Fedora 35 

### ISSUE THREAD

**Issue by joenoone** [corecoding/Vitals#251]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

I did the usual "yum update" today and afterwards I got the GNOME popup notice there was an update for your app. After the update it give me the "ERROR" on the GNOME extensions page (i.e. I can't run it).

### Steps to reproduce the unexpected behavior.

Reloaded GNOME shell extensions page

### What distribution and version of Linux are you using?

Fedora 35

### What version of Gnome are you using?

41.4

**Comment by corecoding** [comment]
Please take a look at this: https://github.com/corecoding/Vitals/wiki/Broken-after-upgrade
