### ISSUE TITLE
data is replaced by points in the bar on ubuntu 22.04

### ISSUE THREAD

**Issue by maravento** [corecoding/Vitals#252]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

should display data instead of ellipses

![Captura desde 2022-04-25 10-33-56](https://user-images.githubusercontent.com/14880802/165144789-67b088a1-d66f-41ce-8732-685a700a1a65.png)

### Steps to reproduce the unexpected behavior.

see error

### What distribution and version of Linux are you using?

ubuntu 22.04

### What version of Gnome are you using?

42

**Comment by pjadczak** [comment]
I have the sam
![Zrzut ekranu z 2022-04-26 13-27-23](https://user-images.githubusercontent.com/45244806/165290197-ba88e55c-d7e8-4d08-88ea-ad8733ae3946.png)
e

**Comment by rungis86** [comment]
Idem on Fedora 35 Gnome 41.5

**Comment by sebastienserre** [comment]
Same issue here

**Comment by corecoding** [comment]
Are you all using English or another language?

**Comment by pjadczak** [comment]
No, I use Polish language.

**Comment by rungis86** [comment]
I'm using french.

1 mai 2022 07:56:44 pjadczak ***@***.***>:

**Comment by sebastienserre** [comment]
French too

**Comment by e7d** [comment]
Hello. I had the same problem a few weeks ago on my Manjaro, that I solved by clicking the refresh button, on the bottom left.
![image](https://user-images.githubusercontent.com/1412033/166432447-fdba7d84-c10a-4704-a941-10b9d6a16aeb.png)

Hope it does the trick for you too!

**Comment by corecoding** [comment]
I have identified the issue. The issue was that for non English installs, it was trying to resolve Memoria instead of Memory (for example). The fix has been uploaded and should be available within a few days.

**Comment by corecoding** [comment]
New version just released.
