### ISSUE TITLE
Weird round borders in preferences 

### ISSUE THREAD

**Issue by dasnoopy** [corecoding/Vitals#255]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

Vital extensions ver. 54: 

Noticed recently, but all sensors preferences  window has round  borders inside the windows itself.

Theme is  Gnome v42 default **adwaita**  with close button on the left..

an example:
![Screenshot from 2022-05-05 20-46-06](https://user-images.githubusercontent.com/296922/167003991-392e7662-d407-4e11-af1a-6690b5e85d44.png)

regards

### Steps to reproduce the unexpected behavior.

1) open the settings windows
2) open any of  sensors preference window
3) look corners inside the window

### What distribution and version of Linux are you using?

archlinux 64bit

### What version of Gnome are you using?

gnome 42.1

**Comment by corecoding** [comment]
I have a fresh copy of Arch with the latest vitals version. It looks fine to me.
![Screenshot from 2022-05-12 23-53-45](https://user-images.githubusercontent.com/3803591/168208262-be67a435-fbc6-46f2-8c92-7b9baa408f5c.png)
 
The preferences UI is generated from prefs.ui - it controls the elements by not the pixels/styling.

**Comment by dasnoopy** [comment]
opss.. forgotten that I was playing with  ./config/gtk-4/gtk.css file... 

this "setting"  is the culprit
```
/* less rounded windows border */
window { border-radius: 8px; }
```

sorry and thanks for your time
