### ISSUE TITLE
Add GPU temperature reading

### ISSUE THREAD

**Issue by ironWolf1990** [corecoding/Vitals#259]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

Able to see GPU temperature would be a nice addition

**Comment by corecoding** [comment]
Please see here for more info https://github.com/corecoding/Vitals/wiki/Can-you-add-support-for-my-GPU%3F
Also, if you have an AMD, please chime in here https://github.com/corecoding/Vitals/issues/124
