### ISSUE TITLE
Show the highest temperature

### ISSUE THREAD

**Issue by sojusnik** [corecoding/Vitals#270]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

In addition to the average temperature of all sensors, it would help if we would have an entry to show the highest temperature of all sensors. This would come in handy to have at the top bar, to see if one of the sensors is too hot.

**Comment by corecoding** [comment]
This was released part of #277. Thank you for the suggestion.
