### ISSUE TITLE
Hide empty sections

### ISSUE THREAD

**Issue by Yaya-Cout** [corecoding/Vitals#276]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

On my laptop, fan speed isn't available, but the section still visible, with a “no data” label. It would be great to have an option to hide these sections.
![Vital menu with no fan screenshot](https://user-images.githubusercontent.com/67095734/184179819-c71ff395-f8e5-416e-aa38-0e9858a07f4c.png)

**Comment by corecoding** [comment]
Go to the extension settings and uncheck Monitor Fan.

**Comment by Yaya-Cout** [comment]
Yes, but an automatic setting would be great

**Comment by corecoding** [comment]
An automatic update isn't possible. Most fans report 0 when the computer is idle. 0 is also used for a fan header that isn't hooked up. If I hide the fan section automatically, it would hide and show sporadically making it confusing to the user. Thanks for the idea. :)
