### ISSUE TITLE
Only able to see 3 sensors

### ISSUE THREAD

**Issue by MisterHarrow** [corecoding/Vitals#278]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

To be able to see all sensors that are checked in the settings.

![image](https://user-images.githubusercontent.com/18102007/184505148-75266650-3e8c-492d-97d3-ae63d9febea9.png)

### Steps to reproduce the unexpected behavior.

I check and de-check options but nothing changes.
I can see the sensor data when I click on the extension but they don't show in the bar.

![image](https://user-images.githubusercontent.com/18102007/184505194-cc370504-9d87-4a6c-93f0-e3df5f9ed43d.png)

How can I sort this out?

### What distribution and version of Linux are you using?

Ubuntu 22.04

### What version of Gnome are you using?

42.2

**Comment by corecoding** [comment]
https://github.com/corecoding/Vitals/wiki/Can't-add-sensors-to-panel
