### ISSUE TITLE
An easier way to reorganize the elements

### ISSUE THREAD

**Issue by brunofunnie** [corecoding/Vitals#290]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

I know we can reorganize the elements by enabling/disabling in a certain order, but it would be great to have a drag 'n drop way of doing that, it would be much more pratical.

**Comment by HubKing** [comment]
Why is it closed? I don't see any way to re-order the items in the Top Bar? How do I re-order items?
