### ISSUE TITLE
Temperature panel shows CPUs that do not exist

### ISSUE THREAD

**Issue by cristiioan** [corecoding/Vitals#293]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

Hello, 
I have an Alder lake(i7-1280P: 6P cores + 8 E cores) system and the temperature panel shows temps for CPUs that do not exist (like CPU 20,24,24,26...31)
![image](https://user-images.githubusercontent.com/67168425/194692709-c9000f65-5f9c-48c5-b4c1-1b713a8a22a8.png)

### Steps to reproduce the unexpected behavior.

Just look at temperature on an alder lake system

### What distribution and version of Linux are you using?

Arch Linux

### What version of Gnome are you using?

42

**Comment by corecoding** [comment]
I don't have access to an Alder lake system. Can you show me the contents of /proc/cpuinfo ? I am also curious if you can send me a screenshot of the System Monitor on the Resource tab. My guess is that this is how the Linux kernel currently is reporting these cores.

**Comment by cristiioan** [comment]
Both /proc/cpuinfo and system monitor show the correct numbers

**Comment by corecoding** [comment]
Will re-open if there is interest.
