### ISSUE TITLE
Fan Speed adjustment/fan curve

### ISSUE THREAD

**Issue by dnaugh** [corecoding/Vitals#318]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

I read down the list and noticed that there were a few people that had similar requests/issues but I wasn't sure if this was a 100% covered issue as I am very new to linux and worried about my computers health in terms of temps

**Comment by corecoding** [comment]
Thank you for the suggestion. Vitals reads values and doesn't set/change them. I can appreciate the allure, but there are scenarios where one could set an invalid rpm or curve value and ruin the hardware. This is an area I don't want to even get close to.
