### ISSUE TITLE
Processor utilization should show at top bar

### ISSUE THREAD

**Issue by ss-vijayvavdiya** [corecoding/Vitals#348]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

Currently processor utilization monitor status is not showing in the top bar. It will help to quickly monitor/check the current utilization of processor when the developer runs the processor incentive code or process, sometimes system slows down and hangs.

**Comment by corecoding** [comment]
Take a look here. https://github.com/corecoding/Vitals/wiki/Can't-add-sensors-to-panel
