### ISSUE TITLE
wrong device rx speed

### ISSUE THREAD

**Issue by imareo** [corecoding/Vitals#351]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

device rx speed looks like the sum of port speed plus same port vpn connection speed

### Steps to reproduce the unexpected behavior.

![Screenshot from 2023-05-19 08-57-34](https://github.com/corecoding/Vitals/assets/46757141/73bd7c75-317c-4d08-a75e-a11a0ff0c2d5)

### What distribution and version of Linux are you using?

fedora 38

### What version of Gnome are you using?

44

**Comment by corecoding** [comment]
Can you add your notes to #319? This will be handled there. Thank you!
