### ISSUE TITLE
Please add an option to change the dashboard info

### ISSUE THREAD

**Issue by AspieSoft** [corecoding/Vitals#358]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

Please add an option to change the dashboard info that gets displayed.
By default, the memory, system, and network are shown on the dashboard. It would be nice to be able to swap out what info always shows on the dashboard be default.
thanks.

**Comment by corecoding** [comment]
Good news! Vitals supports this feature. Please see https://github.com/corecoding/Vitals/wiki/Can't-add-sensors-to-panel
