### ISSUE TITLE
Menu icons without margin

### ISSUE THREAD

**Issue by arononak** [corecoding/Vitals#363]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

i read your code and i removed margin from Circles and PopupMenu in my extension :)

https://github.com/arononak/github-actions-gnome-extension

**Comment by corecoding** [comment]
What is this feature request about? Are you asking for margin to be reduced somewhere?

**Comment by arononak** [comment]
I thought looking at the code that you were trying to remove it. Many extensions have a left margin in a PopupMenu's, because Gnome API has a not obvious structure

**Comment by corecoding** [comment]
Ahh, I see the code... `x.remove_all_children();` - I don't think I can use this. My extension uses the left margin for a checkbox which denotes when a sensor is to be shown in the panel.
![Screenshot from 2023-07-22 13-01-34](https://github.com/corecoding/Vitals/assets/3803591/64ca3fd8-4b89-48d1-9aec-d103e09815a6)

**Comment by arononak** [comment]
You rule here. In the parent item too, you can remove the margin as you like. I spent a few hours on this 😄

But Gnome in new versions use check icon right for WiFi, Bluetooth etc.
