### ISSUE TITLE
vitals for ubuntu 22.04 has status bar arrangement problem

### ISSUE THREAD

**Issue by History-exe** [corecoding/Vitals#368]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

Enabte vitals on ubuntu 22.04, figures show up well. But when I open programs, the up left corner of the desktop interface as well as the status bar always remains the blank in the left of the vitals figures.

For describe this problem in detail, please read the picture below:
![vitalsBugReport](https://github.com/corecoding/Vitals/assets/33642965/786ec435-5dad-4076-95de-8ae0767c0b8a)

### Steps to reproduce the unexpected behavior.

For example:
1. open Firefox.
2. then use the hotkey ctrl + D to back to the desktop
3. there is a blank on the left of vitals figures on the status bar, and the blank length is just same as the length when the Firefox on frontpage.

### Relevant log output

```shell
Sorry for no logs paste, I think this problem is easily observed.
```

### What distribution and version of Linux are you using?

Ubuntu 22.04.3 LTS x86_64

### What version of Gnome are you using?

GNOME 42.9

**Comment by corecoding** [comment]
Unfortunately I don't have time to go back and update old extensions designed for Gnome prior to v45. I would have to run Linux in VM's which is very tedious. I will say this issue seems similar to https://github.com/corecoding/Vitals/issues/373.
