### ISSUE TITLE
  Place it slightly above 1px, the placement is not in the middle.

### ISSUE THREAD

**Issue by TeaHistoria** [corecoding/Vitals#371]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

You can see that the panel comparison between quick settings and vitals results in less aesthetics.
![Screenshot from 2023-09-01 00-57-39](https://github.com/corecoding/Vitals/assets/129779202/50770d51-c472-423b-baf8-a66f56c9c4ed)
![Screenshot from 2023-09-01 00-57-54](https://github.com/corecoding/Vitals/assets/129779202/ae41ba28-1577-4094-8b09-1607f6a81d85)

**Comment by corecoding** [comment]
I appreciate the suggestion! I am not a fan of text floating on the top, unless there is text on the bottom s well (two lines), such as the https://github.com/corecoding/Vitals/issues/198 request.
