### ISSUE TITLE
Adding Mission Center as an alternative for System Monitor

### ISSUE THREAD

**Issue by KaiserCalm** [corecoding/Vitals#379]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

It would be really neat if we could customize what the button to open the System Monitor app does when clicked.
It could either be made to open a user defined app or some apps from a list predefined list (apps like [Mission Center](https://missioncenter.io/)).
![image](https://github.com/corecoding/Vitals/assets/81613945/22fc4dd4-c300-433d-8989-9b8005dcb680)

**Comment by KaiserCalm** [comment]
Sorry, I thought I saw this issue as complete in the pull requests section, but just didn't notice where to do this in the extension settings. Reopening.

**Comment by corecoding** [comment]
Click on the cog/gear icon to go to settings. Then click the cog icon next to Monitor system.

**Comment by KaiserCalm** [comment]
How would I add a flatpak in that setting as flatpak run, is not recognized as a command.

**Comment by KaiserCalm** [comment]
@corecoding How would I add a flatpak in that setting as flatpak run, is not recognized as a command.

**Comment by KaiserCalm** [comment]
![image](https://github.com/corecoding/Vitals/assets/81613945/daaa0b29-6661-400c-a1da-c844b4092ef3)

**Comment by corecoding** [comment]
I'm not sure.. I'm assuming mission-center is not in your path. If you open Terminal and type mission-center, I would assume it would return the same error. The binary needs to be in your path, or enter the full path in Vitals.

**Comment by KaiserCalm** [comment]
I just used the full path to mission center which in my case was:
`/home/user/.local/share/flatpak/exports/bin/io.missioncenter.MissionCenter`
