### ISSUE TITLE
More then one storage

### ISSUE THREAD

**Issue by evgnor86** [corecoding/Vitals#383]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

Hello! Thanks for you work!

Can you add option for more then one storage? More people have many then one disk/partion.

**Comment by Winson-Huang** [comment]
duplicate of #143
