### ISSUE TITLE
CPU fan "Arctic Freezer 33 eSports ONE" is shown as "amdgpu fan1"

### ISSUE THREAD

**Issue by kali010101** [corecoding/Vitals#392]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

Hi, I have an "Arctic Freezer 33 eSports ONE" fan on my Intel i5 CPU which I think is being shown as my GPU's fan.
My GPU is an RX580 (which is at 0 rpm when Im not gaming) and I also have bequiet SilentWings case fans installed.
The GPU fan is shown as running even though it's the only one not running at all.
My mainboard is a Gigabyte B360M H.
Can I somehow display fan speeds of both CPU fan and GPU fan?

![Screenshot from 2023-12-27 18-44-54](https://github.com/corecoding/Vitals/assets/153381455/5ce2a314-e29c-4fb4-93a3-b5181909db23)

EDIT: apparently lm_sensors is reading my system incorrectly?
![Screenshot from 2023-12-28 10-49-36](https://github.com/corecoding/Vitals/assets/153381455/fb919486-2335-41ed-9fd5-501c76ef1a61)

### Steps to reproduce the unexpected behavior.

Just look at it while having the same hardware installed

### What distribution and version of Linux are you using?

Fedora Workstation 39

### What version of Gnome are you using?

45.2

**Comment by corecoding** [comment]
`sensors` uses the same approach as Vitals - that is, it reads data from `/proc` and `/sys`. The `sensors` confirms that this is not a bug, but the way in which the Linux Kernel is reporting your fan data. The good news is that there is an open issue requesting the ability to change sensor text. https://github.com/corecoding/Vitals/issues/83
