### ISSUE TITLE
Please add indicator spacing

### ISSUE THREAD

**Issue by the0demiurge** [corecoding/Vitals#41]
The default no-spacing indicator is somewhat too compact
![image](https://user-images.githubusercontent.com/11363529/46057053-41e36480-c186-11e8-976b-ffb70d6dda35.png)
Expecially when adding public ip address, the top bar seems really messy

Thanks for your work :)

**Comment by jacobrsv** [comment]
Some spacing would make it perfect

![screenshot from 2018-10-29 09-26-00](https://user-images.githubusercontent.com/35469341/47637745-f5ac8b00-db5c-11e8-963d-91b581251b4e.png)

**Comment by corecoding** [comment]
What distro, and gnome version are you guys using? I have spacing on my icons, as shown in the picture on gnome-extensions. If I can duplicate this I can look into fixing it. If you guys are adventurous, there is a .css file in the .local/share/gnome-shell/extensions/Vitals@CoreCoding.com directory, if you make a change press ALT-F2 then type in 'r' to reload gnome. Let me know.

**Comment by jacobrsv** [comment]
I discovered that the missing spacing is caused by the Unite extension https://extensions.gnome.org/extension/1287/unite/
in my case anyways

**Comment by corecoding** [comment]
Thank you. I have also confirmed this. I will reach out to the author of that plugin and see if they have advice.

**Comment by corecoding** [comment]
The author of Unite helped me fix the issue in #51 . By chance can you clone the repo and see if it is fixed on your end?

**Comment by jacobrsv** [comment]
It is looking great now, thanks!

![screenshot from 2018-11-09 11-05-16](https://user-images.githubusercontent.com/35469341/48256404-b9f0ab80-e40f-11e8-90be-f4eba4055220.png)

**Comment by the0demiurge** [comment]
Yes, it looks great, thank u 4 ur work:)
