### ISSUE TITLE
Gnome 46 version doesn't change position til after a logout or reboot

### ISSUE THREAD

**Issue by CharoSW** [corecoding/Vitals#412]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

The position of the menu/stat counter should change based on the option selected

### Steps to reproduce the unexpected behavior.

1. try to change the position on Gnome 46

### What distribution and version of Linux are you using?

Fedora 40, Gnome OS Nightly

### What version of Gnome are you using?

46

**Comment by corecoding** [comment]
Did this occur once, or is it reproducible every time?

**Comment by corecoding** [comment]
An update for this bug has been submitted and should be approved within 24 hours. Thank you!
