### ISSUE TITLE
Warning at start start on gnome-shell 3.30

### ISSUE THREAD

**Issue by terencode** [corecoding/Vitals#42]
``Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).
                                                  (Note that array.toString() may have been called implicitly.)
                                                  0 File.prototype.read/</<() ["/home/terence/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com/helpers/file.js":21]``

**Comment by corecoding** [comment]
Thank you. What distro are you using that has 3.30?

**Comment by terencode** [comment]
Thank you for the extension ;)
Sorry for not mentioning, I'm using ArchLinux.

**Comment by tingvarsson** [comment]
@corecoding here is an example of how to fix similar issues and keep backwards comp: https://github.com/ethanwharris/gnome-nvidia-extension/pull/166

**Comment by corecoding** [comment]
Thanks tingvarsson!

Are you or terencode able to test? I just push the change to master. :)

**Comment by terencode** [comment]
Tested and works, thanks.
