### ISSUE TITLE
Each refresh causes microstutter on gnome

### ISSUE THREAD

**Issue by Pesc0** [corecoding/Vitals#425]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

Each refresh causes microstutter, independent of graphical application: browser, games ...

### Steps to reproduce the unexpected behavior.

Enable the extension. Open a graphical application where you can clearly see the refresh rate. For example: https://www.testufo.com/mprt 
Notice stutters each time the extension fetches an update.
Disable extension and problem is fixed.

### What distribution and version of Linux are you using?

arch

### What version of Gnome are you using?

46, but i'm pretty sure this was happening in earlier versions as well

**Comment by Pesc0** [comment]
fetching just the pinned values when the menu is closed would already be a good optimization to mitigate this (and in general) I think

**Comment by corecoding** [comment]
Please see the wiki entry on this topic: https://github.com/corecoding/Vitals/wiki/System-periodically-freezes

**Comment by Pesc0** [comment]
Thank you! Sorry for the false report, I must have missed that when going trough the wiki.
