### ISSUE TITLE
Change the shortcut for system monitor

### ISSUE THREAD

**Issue by Jooosl** [corecoding/Vitals#428]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

Let me choose what application to open when clicking on the system monitor shortcut inside the menu. Personally, I want to change it to the "resources" application.

Thanks in Advance.

**Comment by corecoding** [comment]
This is available. Go to Preferences, and click the cog next to `Monitor system`.
