### ISSUE TITLE
Ignore sensors reporting impossible value

### ISSUE THREAD

**Issue by terencode** [corecoding/Vitals#43]
I have a faulty temperature sensor returning -128°C, this is taken in account and thus mess up the average temperature.

**Comment by corecoding** [comment]
I have pushed a fix in #44. It will take a little time before it gets into gnome extension but if you want to check it out you can pull the code before then. :) Closing now, will open if the issue is not fixed

**Comment by terencode** [comment]
Thanks, but it's still not fixed. I'm using your extension from master.

**Comment by corecoding** [comment]
Do you have "Hide zero values" turned on?

**Comment by terencode** [comment]
I had it, but disabling it doesn't change anything for the negative values.

**Comment by corecoding** [comment]
By chance do you know the full path and input value of the invalid sensor in the /sys/class/hwmon directory?

**Comment by terencode** [comment]
I do: 

> cat /sys/devices/platform/it87.656/hwmon/hwmon3/temp3_input
> -128000

**Comment by corecoding** [comment]
Can you try one more time? Do a git pull on master then alt-f2 then r
You may have to toggle the checkbox once

**Comment by terencode** [comment]
My bad, I forgot to remove the extension installed from the website which was overwriting the new one installed in /usr/share. It's working correctly now.
Your first fix was enough.

**Comment by badoughatcher** [comment]
I wanted to re-raise this because nouveau reports a 511 degree tempature constantly, this seems to be a known issue. Can we adjust for this too?

![image](https://user-images.githubusercontent.com/8753446/62804387-1c6bfa80-babb-11e9-884e-157890db530b.png)

**Comment by corecoding** [comment]
I am hesitant to change temperature values because if there was a bug, and another sensor was misreported, that would be bad. That being said, have a look at /etc/sensors3.conf - this file allows you to offset temperature values. I have plans to parse this file in Vitals.

**Comment by catto24** [comment]
hi! yet another re-raise - i have quite a few sensors reporting extremely incorrect temperatures, but i have no idea how to ignore them. they've already been ignored in /etc/sensors3.conf but i had a quick look in the directory for Vitals and being real i have no idea how to program in JavaScript...

<img width="596" height="1080" alt="Image" src="https://github.com/user-attachments/assets/95c24236-2f7f-459c-8f07-2987c2948177" />

<img width="596" height="1080" alt="Image" src="https://github.com/user-attachments/assets/4f9afbd4-1917-4139-9661-79a035a70777" />
