### ISSUE TITLE
Gap space on gnome status bar.

### ISSUE THREAD

**Issue by truongvantuan** [corecoding/Vitals#452]
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

I got gap space on the gnome status bar.

### Steps to reproduce the unexpected behavior.

1. Enable Vitals extension.
2. See as screen capture.
![image](https://github.com/user-attachments/assets/8260e8ca-78a9-4515-be5e-0b9e2491ea62)

### What distribution and version of Linux are you using?

Fedora 41

### What version of Gnome are you using?

47

**Comment by matsonkepson** [comment]
HI 
i do have exact opposite problem with Ubuntu 22.04, gnome 42.9. 
I haven't seen anything on logs , if needed i can create a separate issue.
Check the screen below

![image](https://github.com/user-attachments/assets/571332b6-00f0-455a-9ea1-20c1edc340e0)

**Comment by truongvantuan** [comment]
@matsonkepson Yeah, it is sometimes bro. But I don't know when it happened. You can see it is working properly now.
![image](https://github.com/user-attachments/assets/176941d2-8bd1-44e4-b032-fbda57c2a09c)

**Comment by truongvantuan** [comment]
The issue occurs sometimes.
