### ISSUE TITLE
"Alphabetize sensors" sorting

### ISSUE THREAD

**Issue by auipga** [corecoding/Vitals#52]
Cores (0-7) are well sorted but load is 15m, 1m, 5m which is worth improve.

Use Natural sort order ([wiki](https://en.wikipedia.org/wiki/Natural_sort_order))

**Comment by corecoding** [comment]
Thank you. I have added this in #53. It works for me, please test and close this issue if you agree. :+1: It is not yet on Gnome Extensions, so you'll have to checkout master.

**Comment by auipga** [comment]
Thank you
