### ISSUE TITLE
Update POT file

### ISSUE THREAD

**Issue by pkomur** [corecoding/Vitals#58]
Please update POT file. Some strings are missed.

**Comment by corecoding** [comment]
Can you pull the master branch? I recently updated the pot file. If I am still missing some, please let me know which ones.

**Comment by pkomur** [comment]
Missed:
 Core
 Package id
 Uptime
 Used Cycles
 Format
 Bytes
 Bits

**Comment by corecoding** [comment]
Thanks for the feedback.

Core  -  already there
Package id  -  This string comes from the system itself.
Uptime - Added.
Used Cycles - renamed to Process Time. Added. 
Format - added.
Bytes - added.
Bits - added.

**Comment by corecoding** [comment]
Are you working on adding a translation?

**Comment by pkomur** [comment]
Yes, I am.

**Comment by pkomur** [comment]
What is the difference between Uptime and Process Time? It looks like the same.

**Comment by corecoding** [comment]
Process time is the time the cpu spends working - that is, not idle. https://en.m.wikipedia.org/wiki/CPU_time

**Comment by pkomur** [comment]
Thanks

**Comment by corecoding** [comment]
Thank you so much for your work here. You did more than just the Polish translation. I appreciate it.
