### ISSUE TITLE
Icon to Text Spacing / Padding

### ISSUE THREAD

**Issue by msoose** [corecoding/Vitals#61]
Either icon sizes are different, or text between icon spacing should be user-configurable. 

When enabling either Memory, Processor, System, or Network icon indicators, the spacing is too close between the icon and the text. The values are almost touching the icon.

Temperature has perfect spacing, Storage is slightly off, but not as bad as the aforementioned.

**Comment by corecoding** [comment]
Addressed in develop branch.
