### ISSUE TITLE
Default info config

### ISSUE THREAD

**Issue by trailjeep** [corecoding/Vitals#67]
It would be nice to configure the default info shown in the panel.  For example, show network speed and I could eliminate [NetSpeed](https://extensions.gnome.org/extension/104/netspeed/) extension.

**Comment by corecoding** [comment]
You can! Click the speed in the drop down menu. It will appear in the menu bar. Click again to remove.

**Comment by carloshkayser** [comment]
Hello @corecoding,
I would like to back up my panel configuration (preferences), where is this information saved? 
Thanks for this awesome extension!
