### ISSUE TITLE
Add disk io section

### ISSUE THREAD

**Issue by terencode** [corecoding/Vitals#69]
It would be nice to have per disk as well as global read/write speed.

**Comment by corecoding** [comment]
WIP - https://github.com/corecoding/Vitals/tree/disk-io

**Comment by terencode** [comment]
Nice, I'm using it right now with no issue so far.

**Comment by corecoding** [comment]
Closing this issue because the feature has been released for quite some time. From what I remember, it doesn't work with LVM volumes, as there is no way for me to know which LVM pertains to the files in /proc. Also, #143 talks about "per disk" feature
