### ISSUE TITLE
Missing System Monitor icon in Arch

### ISSUE THREAD

**Issue by corecoding** [corecoding/Vitals#77]
Arch Linux has a missing System Monitor icon in Gnome 3.32 mentioned in https://github.com/corecoding/Vitals/issues/74

**Comment by Zappo-II** [comment]
I'm just another user but it works for me on Arch with Gnome 3.32...might be some other individual problem...maybe something icon library related, I'm using adwaita...

**Comment by corecoding** [comment]
Do you happen to know the package name for adwaita?

**Comment by Zappo-II** [comment]
https://www.archlinux.org/packages/?q=adwaita-icon-theme

**Comment by WoefulDerelict** [comment]
The SVG resource used for the System Monitor icon is located in the [gnome-icon-theme-symbolic](https://www.archlinux.org/packages/extra/any/gnome-icon-theme-symbolic/) package. The relevant file is /usr/share/icons/gnome/scalable/apps/utilities-system-monitor-symbolic.svg

**Comment by corecoding** [comment]
Thank you. Will update README with package name.
