### ISSUE TITLE
Hide top bar icons

### ISSUE THREAD

**Issue by kapcom01** [corecoding/Vitals#80]
Hello.
With many extension loaded on the panel it starts to run out of space. It would be helpful if there was an option to hide the icons from the panel. For example, I use this extension to watch my CPU temperature, so a simple "50°C" is enough for me. The thermometer icon does not give me any more information.

Thanks.

**Comment by durapensa** [comment]
Vitals is a fantastic little GNOME Shell extension! I came here to post essentially the same feature request, and a more specific suggestion for the Sensors column of the Preferences window: either in the same column (if possible) or a new 'Status Icons' column, provide tick-boxes or "light switch" style toggles to toggle the display of individual sensor icons in the status area, and an ability to re-order said icons. Many thanks for working on this extension and for keeping it up-to-date!

**Comment by KonstantMan** [comment]
Yeah that would be really nice option to avoid cluttering all the icons togethere

**Comment by xcodz-dot** [comment]
Hey there, Any idea if its being worked on or kept for later?

**Comment by corecoding** [comment]
I will add this feature to the next release, seems that enough of you want this feature. I missed the 12 thumbs ups. :)

**Comment by corecoding** [comment]
This feature is available for testing in the development branch. Please test it and let me know if it is working.

Instructions for beta testing are listed in the README at https://github.com/corecoding/Vitals under Beta Testing

**Comment by spxak1** [comment]
> This feature is available for testing in the development branch. Please test it and let me know if it is working.
> 
> Instructions for beta testing are listed in the README at https://github.com/corecoding/Vitals under Beta Testing

Installed and looks great! Thank you.

**Comment by corecoding** [comment]
Vitals 46 released with this feature.
