### ISSUE TITLE
[Feature Request] Let user define which sensors are shown in the tray

### ISSUE THREAD

**Issue by BjoernDaase** [corecoding/Vitals#81]
It would be great if a user could decide which sensors are show in the tray instead of always showing `Memory` and `System`.

**Comment by corecoding** [comment]
You can. Just click the sensor that you want to hide/show in the menu drop down itself. 

Christopher Monahan

**Comment by BjoernDaase** [comment]
@corecoding Ah, perfect, found it!
Maybe you could put a link to the wiki page into the README, then it's easier to find :+1:
