### ISSUE TITLE
Missing Mhz Text in Arch Linux

### ISSUE THREAD

**Issue by zsantos** [corecoding/Vitals#82]
Hello, I noticed that on Arch Linux the Mhz text does not appear, is it required to install any particular font ? I have a manjaro system with the same extension and it is working perfectly, just wondering if I am missing anything. 

Thank you for your time.

![image](https://user-images.githubusercontent.com/26259716/56590503-225ad000-65df-11e9-8fab-ac949bea690d.png)

**Comment by corecoding** [comment]
Thanks. I think I will make this change going forward. I was using Unicode characters to save space in the menu bar. Optionally I can add a checkbox but that seems kind of silly.

**Comment by zsantos** [comment]
@christhejoker Thanks mate that did it. Have a good one
