### ISSUE TITLE
[Feature Request] Second Fan Monitor

### ISSUE THREAD

**Issue by tye-mustafa** [corecoding/Vitals#84]
i have a Dell 7559 which have two integrated fans. your extension only show one fan.
![Screenshot from 2019-05-15 03-49-08](https://user-images.githubusercontent.com/26303106/57737323-b4c52f80-76c4-11e9-9b59-2765b754ec64.png)
on the other side lm-sensors shows both fans and other extensions on gnome also shows both fans in there extensions.
![Screenshot from 2019-05-15 03-52-44](https://user-images.githubusercontent.com/26303106/57737382-ed650900-76c4-11e9-8f08-14afb7d62fce.png)

please add both fans monitor system.

**Comment by corecoding** [comment]
Can you check out the develop branch (instructions on the README) by following step 2a then git checkout develop, then restart gnome? The second fan should show Processor Fan 2

**Comment by corecoding** [comment]
Closing. Feel free to reply, and if it doesn’t work I’ll reopen the issue.
