### ISSUE TITLE
Can an option to show CPU Temperature and Fan Speed on the Shell be possible?

### ISSUE THREAD

**Issue by xzj8b3** [corecoding/Vitals#87]
Is it possible to add a small option to show on the Shell bar the CPU temperature and fan revolutions so you always have them under control?

**Comment by corecoding** [comment]
FAQ: Click sensors in drop-down menu to show/hide in panel menu!

**Comment by xzj8b3** [comment]
> FAQ: Click sensors in drop-down menu to show/hide in panel menu!

The clear one, but it would be more useful displaying temperature and fan on the bar so you always have them in sight

**Comment by corecoding** [comment]
You can do this today. Click the fan and temperature that you want on the bar.
