### ISSUE TITLE
Storage not shown

### ISSUE THREAD

**Issue by ozls** [corecoding/Vitals#94]
I just discovered this extension and I love it. But unfortunately, the storage is not showing any kind of drop down menu. I saw issue #45 and it looks like my problem, but restarting the shell did nothing. Is there something that I am missing ? I have Ubuntu 18.04.2 with GNOME 3.28.2.

**Comment by corecoding** [comment]
Please install the packages mentioned in the README file.

**Comment by ozls** [comment]
Oops. Thank you for the answer, I'm very sorry for being a non-readme-reading asshole :-D Have a nice day !

**Comment by liver** [comment]
Storage not showing...
![image](https://github.com/corecoding/Vitals/assets/2996212/c0cc8fac-e8cd-4551-a2bd-20479d775c54)

**Comment by liver** [comment]
> Storage not showing... ![image](https://user-images.githubusercontent.com/2996212/259008813-c0cc8fac-e8cd-4551-a2bd-20479d775c54.png)

solution:
sudo apt install gir1.2-gtop-2.0 lm-sensors

than, reboot system

**Comment by youyoumu** [comment]
for NixOS users, you should install the extension from [gnomeExtensions.Vitals](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=gnomeExtensions.Vitals) package. It has the necessary patch to find libgtop
