### ISSUE TITLE
error: TypeError: menuItems[i].key is undefined

### ISSUE THREAD

**Issue by vak** [corecoding/Vitals#99]
GitHab version and the version 21 for gnome 1:3.30+1ubuntu1 gives this error and the extension isn't loaded.

As for version 21 it happens here:
/home/vak/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com/extension.js:392 

Last extension version without this error is the version 19. 
The version 20 is already affected

**Comment by corecoding** [comment]
Will submit a fix tonight. Unfortunately it may take a few weeks for Gnome team to approve it.
